name: "Build And Deploy"

on: [push]

env:
	AZURE_WEBAPP_NAME: aspnet-core-sample-deploy #set this to your application name
	AZURE_WEBAPP_PACKAGE_PATH: './published'     #set this to the path to your webapp proj
	NETCORE_VERSION: '5.0'

jobs:
	build:
		name: Build and Deploy
		runs-on: ubuntu-latest
		steps:
		-uses: actions/checkout@v2

		-name: Setup .Net Cores SDK ${{ env.NETCORE_VERSION }}
		uses: actions/setup-dotnet@v1
		with:
		  dotnet-version: ${{ env.NETCORE_VERSION }}

		-name: Restore
		 run: dotnet restore

		-name: Build
		 run: dotnet build --no-restore -c Release

		-name: Publish
		 run: dotnet publish --no-build -c Release -o ./published 

		 -name: 'Deploy to Azure WebApp'
		 uses: azure/webapps-deploy@v2
		 with:
			app-name: ${{ env.AZURE-WEBAPP_NAME }}
			publish-profile: ${{ seccrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
			package: ${{env.AZURE_WEBAPP_PACKAGE_PATH }}
